version = 1

# Data and documents
[[annotations]]
path = [
  "**/*.csv", 
  "**/*.doc", 
  "**/*.docx", 
  "**/*.pdf",
  "**/*.xls", 
  "**/*.xlsx"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Colaboradores de apuntes_muicd_uned"
SPDX-License-Identifier = "CC-BY-4.0"

# Source codes and notebooks that do not accept embedded license annotations
[[annotations]]
path = [
  "**/*.ipynb"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Colaboradores de apuntes_muicd_uned"
SPDX-License-Identifier = "MIT"