version = 1

# Data and documents
[[annotations]]
path = [
  # Data files
  "**/*.csv", 
  # Office documents
  "**/*.doc", 
  "**/*.docx", 
  "**/*.pdf",
  "**/*.xls", 
  "**/*.xlsx",
  # Images
  "**/*.gif",
  "**/*.jpeg",
  "**/*.jpg",
  "**/*.png",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Colaboradores de apuntes_muicd_uned"
SPDX-License-Identifier = "CC-BY-4.0"

# Source codes and notebooks that do not accept embedded license annotations
[[annotations]]
path = [
  "**/*.ipynb"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Colaboradores de apuntes_muicd_uned"
SPDX-License-Identifier = "MIT"